name: app
description: Flutter state management patterns.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  badges:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_riverpod:
  freezed_annotation:
  intl:
  provider:
  riverpod_annotation:

dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  pedantic_mono:
  riverpod_generator:

flutter:
  uses-material-design: true

flutter_intl:
  enabled: false
